name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '21 3 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://wildlife.ca.gov/Fishing/Ocean/Regulations/Sport-Fishing/Invertebrate-Fishing-Regs > Invertebrate-Fishing-Regs.html
        curl https://wildlife.ca.gov/Fishing/Ocean/Regulations/Sport-Fishing/Marine-Plants > Marine-Plants.html
        curl https://wildlife.ca.gov/Fishing/Ocean/Regulations/Sport-Fishing/General-Ocean-Fishing-Regs > General-Ocean-Fishing-Regs.html
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
